swagger: "2.0"
info:
  title: RateAll
  version: "1.0"
host: rateall
basePath: /
tags:
  - users
  - —Åharacteristics
  - objects
schemes:
  - https
paths:
  /users:
    get:
      tags:
        - users
      responses:
        '200':
           description: list for all users
           schema:
             type: array
             items:
                $ref: '#/definitions/UserItem'
        '400':
          description: not users
  /users/profile:
    get:
      tags:
        - users
      responses:
        '200':
          description: Ok
  /users/login:
    post:
      tags:
        - users
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserItem'
      responses:
        '200':
          description: Ok
  /users/register:
    post:
      tags:
        - users
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/UserItem'
      responses:
        '200':
          description: Ok



definitions:
  UserItem:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      status:
        type: string
      image:
        type: string
      created:
        type: string
        format: date-time
      updated:
        type: string
        format: date-time
  ObjectItem:
    type: object
    properties:
      owner:
        $ref: '#/definitions/UserItem'
      name:
        type: string
      description:
        type: text
      image:
        type: string
      status:
        type: string
      created:
        type: string
        format: date-time
      updated:
        type: string
        format: date-time
  CharacteristicItem:
    type: object
    properties:
      owner:
        $ref: '#/definitions/UserItem'
      name:
        type: string
      description_plus:
        type: text
      description_minus:
        type: text
      status:
        type: string
      created:
        type: string
        format: date-time
      updated:
        type: string
        format: date-time